#!/usr/bin/env bash

if (($# > 0)); then
  cat >&2 << EOM
Usage: $(basename $0)

Build a skool file using the existing contents of manic_miner.skool and the
snippets produced by mm2skool.py.
EOM
  exit 1
fi

if [[ -z $MANICMINER_HOME ]]; then
  echo "Error: MANICMINER_HOME not defined."
  exit 1
fi
if [[ ! -d $MANICMINER_HOME ]]; then
  echo "Error: directory not found: $MANICMINER_HOME"
  exit 1
fi

mm2skool=$MANICMINER_HOME/utils/mm2skool.py
MM_SKOOL=$MANICMINER_HOME/manic_miner.skool

sed '/^ 33520 .*/q' $MM_SKOOL
echo
$mm2skool sbat | tail -n +3
sed -n '/^; The game has just loaded/,/^ 45040 .*/p' $MM_SKOOL
echo
$mm2skool caverns | tail -n +3
