#!/usr/bin/env bash
set -e # Abort on errors

if [[ -z $MANICMINER_HOME ]]; then
  echo "Error: MANICMINER_HOME not defined."
  exit 1
fi
if [[ ! -d $MANICMINER_HOME ]]; then
  echo "Error: directory not found: $MANICMINER_HOME"
  exit 1
fi

if [[ -z $SKOOLKIT_HOME ]]; then
  echo "Error: SKOOLKIT_HOME not defined."
  exit 1
fi
if [[ ! -d $SKOOLKIT_HOME ]]; then
  echo "Error: directory not found: $SKOOLKIT_HOME"
  exit 1
fi

GAME=mm
GAMEDIR=manic_miner
GAMENAME="Manic Miner"
SRCFILES=$(echo COPYING manic_miner.{skool,ref,css} {bugs,changelog,facts,pokes}.ref {dark,green,plum}.css manicminer.py)
DHOME=$MANICMINER_HOME
GHREPO=manicminer
GHHTMLOPTS="-T plum -j style.css"

. $SKOOLKIT_HOME/tools/drelease-functions

parse_args $*
