#!/usr/bin/env bash
set -e # Abort on errors

if [[ -z $MANICMINER_HOME ]]; then
  echo "Error: MANICMINER_HOME not defined."
  exit 1
fi
if [[ ! -d $MANICMINER_HOME ]]; then
  echo "Error: directory not found: $MANICMINER_HOME"
  exit 1
fi

if [[ -z $SKOOLKIT_HOME ]]; then
  echo "Error: SKOOLKIT_HOME not defined."
  exit 1
fi
if [[ ! -d $SKOOLKIT_HOME ]]; then
  echo "Error: directory not found: $SKOOLKIT_HOME"
  exit 1
fi

DHOME=$MANICMINER_HOME

. $DHOME/.dreleaserc

. $SKOOLKIT_HOME/tools/drelease-functions

parse_args $*
